#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\gametypes\_hud_util;

BoxWeaponText()
{
	switch(level.boxWeapon)
	{
		case "fal_mp": level.guntext = "FN-FAL";
		break;
		case "usp_mp": level.guntext = "USP.45";
		break;
		case "deserteagle_mp": level.guntext = "Desert Eagle";
		break;
		case "tmp_silencer_mp": level.guntext = "^3Flamethrower";
		break;
		case "coltanaconda_mp": level.guntext = ".44 Magnum";
		break;
		case "pp2000_eotech_mp": level.guntext = "^2Raygun";
		break;
		case "glock_mp": level.guntext = "Glock 18";
		break;
		case "beretta393_mp": level.guntext = "M93 Raffica";
		break;
		case "mp5k_mp": level.guntext = "MP5K";
		break;
		case "pp2000_mp": level.guntext = "PP2000";
		break;
		case "uzi_mp": level.guntext = "UZI";
		break;
		case "p90_mp": level.guntext = "P-90";
		break;
		case "m16_shotgun_xmags_mp": level.guntext = "The Peace Keeper ;)";
		break;
		case "kriss_mp": level.guntext = "Vector";
		break;
		case "ump45_mp": level.guntext = "UMP-45";
		break;
		case "tmp_mp": level.guntext = "TMP";
		break;
		case "ak47_mp": level.guntext = "AK-47";
		break;
		case "m16_reflex_mp": level.guntext = "M16A4 Red Dot Sight";
		break;
		case "m4_reflex_mp": level.guntext = "M4A1 Red Dot Sight";
		break;
		case "fn2000_mp": level.guntext = "F2000";
		break;
		case "masada_mp": level.guntext = "Assualt Combat Rifle";
		break;
		case "famas_mp": level.guntext = "Famas";
		break;
		case "scar_mp": level.guntext = "SCAR-L";
		break;
		case "tavor_mp": level.guntext = "TAR-21";
		break;
		case "m79_mp": level.guntext = "Thumper";
		break;
		case "rpg_mp": level.guntext = "RPG-7";
		break;
		case "onemanarmy_mp": level.guntext = "One Man Army";
		break;
		case "barrett_mp": level.guntext = "Barrett M82";
		break;
		case "wa2000_acog_mp": level.guntext = "WA2000";
		break;
		case "m21_acog_mp": level.guntext = "M14 EBR ACOG";
		break;
		case "cheytac_mp": level.guntext = "Intervention Explosive Bolts";
		break;
		case "ranger_mp": level.guntext = "Double Barrel Shotgun";
		break;
		case "model1887_mp": level.guntext = "Model 1887";
		break;
		case "striker_mp": level.guntext = "Striker";
		break;
		case "aa12_mp": level.guntext = "AA12";
		break;
		case "m1014_mp": level.guntext = "M1014";
		break;
		case "spas12_mp": level.guntext = "Spas-12";
		break;
		case "rpd_mp": level.guntext = "RPD";
		break;
		case "sa80_mp": level.guntext = "L86";
		break;
		case "mg4_mp": level.guntext = "MG-4";
		break;
		case "m240_grip_mp": level.guntext = "M240 Grip";
		break;
		case "aug_mp": level.guntext = "AUG-H BAR";
		break;
		case "at4_mp": level.guntext = "AT4-HS";
		break;
		case "m4_silencer_mp": level.guntext = "M4A1 Silencer";
		break;
		case "model1887_fmj_mp": level.guntext = "Model 1887 FMJ";
		break;
		case "javelin_mp": level.guntext = "Javelin";
		break;
		case "beretta_mp": level.guntext = "M9";
		break;
		default: level.guntext = "Unknown Weapon";
		break;
	}
}

UpgradeWeaponText()
{
	level.upgradetext = undefined;
	switch(self getCurrentWeapon())
	{
		case "fal_mp": level.upgradetext = "FN-FAL";
		break;
		case "usp_mp": level.upgradetext = "USP.45";
		break;
		case "deserteagle_mp": level.upgradetext = "Desert Eagle";
		break;
		case "tmp_silencer_mp": level.upgradetext = "^3Flamethrower";
		break;
		case "coltanaconda_mp": level.upgradetext = ".44 Magnum";
		break;
		case "pp2000_eotech_mp": level.upgradetext = "^2Raygun";
		break;
		case "glock_mp": level.upgradetext = "Glock 18";
		break;
		case "beretta393_mp": level.upgradetext = "M93 Raffica";
		break;
		case "mp5k_mp": level.upgradetext = "MP5K";
		break;
		case "pp2000_mp": level.upgradetext = "PP2000";
		break;
		case "uzi_mp": level.upgradetext = "UZI";
		break;
		case "p90_mp": level.upgradetext = "P-90";
		break;
		case "kriss_mp": level.upgradetext = "Vector";
		break;
		case "ump45_mp": level.upgradetext = "UMP-45";
		break;
		case "tmp_mp": level.upgradetext = "TMP";
		break;
		case "ak47_mp": level.upgradetext = "AK-47";
		break;
		case "m16_reflex_mp": level.upgradetext = "M16A4 Red Dot Sight";
		break;
		case "m4_reflex_mp": level.upgradetext = "M4A1 Red Dot Sight";
		break;
		case "fn2000_mp": level.upgradetext = "F2000";
		break;
		case "masada_mp": level.upgradetext = "Assualt Combat Rifle";
		break;
		case "famas_mp": level.upgradetext = "Famas";
		break;
		case "scar_mp": level.upgradetext = "SCAR-L";
		break;
		case "tavor_mp": level.upgradetext = "TAR-21";
		break;
		case "m79_mp": level.upgradetext = "Thumper";
		break;
		case "rpg_mp": level.upgradetext = "RPG-7";
		break;
		case "onemanarmy_mp": level.upgradetext = "One Man Army";
		break;
		case "barrett_mp": level.upgradetext = "Barrett M82";
		break;
		case "wa2000_acog_mp": level.upgradetext = "WA2000";
		break;
		case "m21_acog_mp": level.upgradetext = "M14 EBR ACOG";
		break;
		case "cheytac_mp": level.upgradetext = "Intervention Explosive Bolts";
		break;
		case "ranger_mp": level.upgradetext = "Double Barrel Shotgun";
		break;
		case "model1887_mp": level.upgradetext = "Model 1887";
		break;
		case "m16_shotgun_xmags_mp": level.upgradetext = "The Peace Keeper ;)";
		break;
		case "striker_mp": level.upgradetext = "Striker";
		break;
		case "aa12_mp": level.upgradetext = "AA12";
		break;
		case "m1014_mp": level.upgradetext = "M1014";
		break;
		case "spas12_mp": level.upgradetext = "Spas-12";
		break;
		case "rpd_mp": level.upgradetext = "RPD";
		break;
		case "sa80_mp": level.upgradetext = "L86";
		break;
		case "mg4_mp": level.upgradetext = "MG-4";
		break;
		case "m240_grip_mp": level.upgradetext = "M240 Grip";
		break;
		case "aug_mp": level.upgradetext = "AUG-H BAR";
		break;
		case "at4_mp": level.upgradetext = "AT4-HS";
		break;
		case "beretta_mp": level.upgradetext = "M9";
		break;
		case "m4_silencer_mp": level.upgradetext = "M4A1 Silencer";
		break;
		case "model1887_fmj_mp": level.upgradetext = "Model 1887 FMJ";
		break;
		case "javelin_mp": level.upgradetext = "Javelin";
		break;
		default: level.upgradetext = "Unknown Weapon";
		break;
	}
}

TakeUpgradeWeaponText(weapon)
{
	level.takeupgradetext = undefined;
	self.upgrade = weapon;
	switch(self.upgrade)
	{
		case "ump45_akimbo_rof_mp": level.takeupgradetext = "UMPE-100 Holographic Sight";
		break;
		case "m16_shotgun_xmags_mp": level.takeupgradetext = "The Peace Keeper ;)";
		break;
		case "usp_silencer_xmags_mp": level.takeupgradetext = "Perisher";
		break;
		case "deserteagle_akimbo_mp": level.takeupgradetext = "Mustang & Sally";
		break;
		case "wa2000_acog_xmags_mp": level.takeupgradetext = "^3WAZOO 65";
		break;
		case "m16_eotech_xmags_mp": level.takeupgradetext = "M16A10 Fully Auto Holo Sight";
		break;
		case "famas_acog_fmj_mp": level.takeupgradetext = "Famas Fully Auto Acog Sight";
		break;
		case "beretta393_akimbo_xmags_mp": level.takeupgradetext = "FM93 Super Raffica Akimbo";
		break;
		case "ak47_fmj_xmags_mp": level.takeupgradetext = "AK-47 Extended Mags+FMJ";
		break;
		case "aa12_grip_xmags_mp": level.takeupgradetext = "AAA121 Grip Xmags";
		break;
		case "striker_xmags_mp": level.takeupgradetext = "Killer Extended Mags";
		break;
		case "cheytac_fmj_mp": level.takeupgradetext = "Intervention Super Bullets";
		break;
		case "cheytac_fmj_silencer_mp": level.takeupgradetext = "NoScoper's Delight";
		break;
		case "glock_fmj_silencer_mp": level.takeupgradetext = "Glock-18 Sharpshooter";
		break;
		case "rpd_eotech_grip_mp": level.takeupgradetext = "RPDK Holographic Sight";
		break;
		case "coltanaconda_akimbo_fmj_mp": level.takeupgradetext = "Python Akimbo";
		break;
		case "m4_eotech_shotgun_mp": level.takeupgradetext = "M4A4 Holographic With Shotgun";
		break;
		case "mp5k_fmj_xmags_mp": level.takeupgradetext = "MP5 Extreme Bullets";
		break;
		case "barrett_acog_xmags_mp": level.takeupgradetext = "Merz's Bow";
		break;
		case "sa80_grip_xmags_mp": level.takeupgradetext = "The Grappler";
		break;
		case "m21_acog_xmags_mp": level.takeupgradetext = "M14 Jambo";
		break;
		case "spas12_fmj_mp": level.takeupgradetext = "Anti-Gravity Shotgun";
		break;
		case "tmp_fmj_silencer_mp": level.takeupgradetext = "Blood Rain";
		break;
		case "mg4_eotech_xmags_mp": level.takeupgradetext = "MG-8 Holographic Sight";
		break;
		case "pp2000_fmj_reflex_mp": level.takeupgradetext = "PP4000";
		break;
		case "aug_eotech_xmags_mp": level.takeupgradetext = "ASG LMG Holographic Sight";
		break;
		case "m240_eotech_xmags_mp": level.takeupgradetext = "Makarov";
		break;
		case "tavor_fmj_reflex_mp": level.takeupgradetext = "TAR-21 Mars Sight";
		break;
		case "kriss_reflex_rof_mp": level.takeupgradetext = "Hector";
		break;
		case "scar_reflex_xmags_mp": level.takeupgradetext = "The Chopper";
		break;
		case "ranger_akimbo_fmj_mp": level.takeupgradetext = "Double Barrel Shotgun Akimbo";
		break;
		case "p90_rof_xmags_mp": level.takeupgradetext = "Speakeasy";
		break;
		case "masada_reflex_xmags_mp": level.takeupgradetext = "GaYCR";
		break;
		case "uzi_acog_silencer_mp": level.takeupgradetext = "Super UZI ACOG";
		break;
		case "model1887_akimbo_fmj_mp": level.takeupgradetext = "Arnold PW?NS";
		break;
		case "fn2000_reflex_mp": level.takeupgradetext = "F4000";
		break;
		case "fal_reflex_xmags_mp": level.takeupgradetext = "Ep!c Win";
		break;
		case "m1014_xmags_mp": level.takeupgradetext = "M2028";
		break;
		case "tmp_silencer_xmags_mp": level.takeupgradetext = "Flamethrower Xmags";
		break;
		case "pp2000_eotech_xmags_mp": level.takeupgradetext = "Porters X2 Raygun";
		break;
		case "deserteagle_akimbo_fmj_mp": level.takeupgradetext = "The Matrix";
		break;
		case "ac130_25mm_mp": level.takeupgradetext = "Machine Gun";
		break;
		case "ak47_acog_xmags_mp": level.takeupgradetext = "AK-47 Thermal No Recoil";
		break;
		case "beretta_akimbo_xmags_mp": level.takeupgradetext = "M9 Akimbo Xmags";
		break;
		case "m4_acog_silencer_mp": level.takeupgradetext = "M4A6 ACOG Silencer";
		break;
		case "model1887_akimbo_mp": level.takeupgradetext = "Boomstick";
		break;
		case "javelin_mp": level.takeupgradetext = "Javlin Pro";
		break;
		case "rpg_mp": level.takeupgradetext = "RPG-27";
		break;
		default: level.takeupgradetext = "Unknown Weapon";
		break;
	}
}